# Generated by Django 5.0.6 on 2024-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pps_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='registerstudent',
            old_name='pps_number',
            new_name='password',
        ),
    ]
