# Generated by Django 4.2.13 on 2024-05-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_addstudents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterStudent',
            new_name='RegisterUser',
        ),
    ]
